import { useState, useRef, useEffect } from 'react';
import { getRoleEngineerResponse } from '../services/gemini';
import { Send, User, Bot, Loader2, Sparkles, Trash2, Download, FileText, CheckCircle, Copy } from 'lucide-react';
import { cn } from '../lib/utils';
import Markdown from 'react-markdown';
import { Content } from '@google/genai';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { motion, AnimatePresence } from 'motion/react';

interface ChatMessage {
  role: 'user' | 'model';
  content: string;
  isJson?: boolean;
  parsedData?: RolePackage;
}

interface RolePackage {
  roleName: string;
  systemPrompt: string;
  userPrompt: string;
  examples: { input: string; output: string }[];
  evaluation: string;
  templates: string;
}

export function RoleEngineerChat() {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Initialize with opening message
  useEffect(() => {
    if (messages.length === 0) {
      setMessages([{ 
        role: 'model', 
        content: "**System Status: ACTIVE & READY**\n\nI am your expert Role-Based AI Persona Engineering Specialist. I craft production-grade, platform-optimized role prompts.\n\nHow may I assist you with role engineering today?" 
      }]);
    }
  }, []);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMessage = input.trim();
    setInput('');
    setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setIsLoading(true);

    try {
      // Convert internal message format to Gemini Content format
      const history: Content[] = messages.map(m => ({
        role: m.role,
        parts: [{ text: m.content }] // Send raw content, even if it was JSON previously
      }));

      const response = await getRoleEngineerResponse(history, userMessage);
      
      // Check if response is JSON
      let isJson = false;
      let parsedData: RolePackage | undefined;
      
      try {
        // Extract JSON from code block if present
        const jsonMatch = response.match(/```json\n([\s\S]*?)\n```/);
        const jsonString = jsonMatch ? jsonMatch[1] : response;
        
        const data = JSON.parse(jsonString);
        if (data.roleName && data.systemPrompt) {
            isJson = true;
            parsedData = data as RolePackage;
        }
      } catch (e) {
        // Not JSON, treat as normal text
      }

      setMessages(prev => [...prev, { 
        role: 'model', 
        content: response,
        isJson,
        parsedData
      }]);
    } catch (error) {
      console.error('Chat error:', error);
      setMessages(prev => [...prev, { role: 'model', content: "I'm encountering a system error. Please try again." }]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleClearChat = () => {
    setMessages([{ 
        role: 'model', 
        content: "**System Status: ACTIVE & READY**\n\nI am your expert Role-Based AI Persona Engineering Specialist. I craft production-grade, platform-optimized role prompts.\n\nHow may I assist you with role engineering today?" 
      }]);
  };

  const handleDownloadZip = async (pkg: RolePackage) => {
    const zip = new JSZip();
    const folderName = pkg.roleName.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const folder = zip.folder(folderName);
    
    if (folder) {
        folder.file("system_prompt.md", pkg.systemPrompt);
        folder.file("user_prompt.md", pkg.userPrompt);
        folder.file("evaluation.md", pkg.evaluation);
        folder.file("templates.md", pkg.templates);
        
        const examplesContent = pkg.examples.map((ex, i) => 
            `## Example ${i + 1}\n\n**Input:**\n${ex.input}\n\n**Output:**\n${ex.output}\n`
        ).join("\n---\n\n");
        folder.file("examples.md", examplesContent);
        
        const readmeContent = `# ${pkg.roleName}\n\nGenerated by AI Role Architect.\n\n## Contents\n- system_prompt.md: The core persona instruction\n- user_prompt.md: Instructions for the user\n- examples.md: Sample interactions\n- evaluation.md: Success criteria checklist\n- templates.md: Reusable patterns`;
        folder.file("README.md", readmeContent);
        
        const content = await zip.generateAsync({ type: "blob" });
        saveAs(content, `${folderName}_package.zip`);
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-2rem)] max-w-4xl mx-auto bg-white rounded-2xl shadow-xl overflow-hidden border border-gray-200">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-gray-100 bg-gradient-to-r from-indigo-50 to-purple-50">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-200">
            <Sparkles className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="font-bold text-gray-900 font-display">Role Engineering Specialist</h2>
            <p className="text-xs text-indigo-600 font-medium">Powered by Gemini 2.0 Flash</p>
          </div>
        </div>
        <motion.button 
          whileHover={{ scale: 1.1, rotate: 90 }}
          whileTap={{ scale: 0.9 }}
          onClick={handleClearChat}
          className="p-2 hover:bg-white/50 rounded-full transition-colors text-gray-500 hover:text-red-600"
          title="Clear Chat"
        >
          <Trash2 className="w-5 h-5" />
        </motion.button>
      </div>

      {/* Chat Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-6 bg-gray-50/30">
        <AnimatePresence initial={false}>
          {messages.map((msg, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              transition={{ duration: 0.3 }}
              className={cn(
                "flex gap-3 max-w-[95%]", // Wider for package display
                msg.role === 'user' ? "ml-auto flex-row-reverse" : ""
              )}
            >
              <div className={cn(
                "w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 shadow-sm",
                msg.role === 'user' ? "bg-indigo-600 text-white" : "bg-white text-indigo-600 border border-gray-200"
              )}>
                {msg.role === 'user' ? <User className="w-4 h-4" /> : <Bot className="w-4 h-4" />}
              </div>
              
              <div className={cn(
                "p-4 rounded-2xl shadow-sm text-sm leading-relaxed w-full",
                msg.role === 'user' 
                  ? "bg-indigo-600 text-white rounded-tr-none max-w-fit" 
                  : "bg-white text-gray-800 border border-gray-100 rounded-tl-none"
              )}>
                {msg.isJson && msg.parsedData ? (
                  <div className="space-y-4">
                      <div className="flex items-center justify-between border-b border-gray-100 pb-3">
                          <div>
                              <h3 className="text-lg font-bold text-gray-900 flex items-center gap-2 font-display">
                                  <CheckCircle className="w-5 h-5 text-green-500" />
                                  {msg.parsedData.roleName} Package
                              </h3>
                              <p className="text-xs text-gray-500">Ready for deployment</p>
                          </div>
                          <motion.button
                              whileHover={{ scale: 1.05 }}
                              whileTap={{ scale: 0.95 }}
                              onClick={() => msg.parsedData && handleDownloadZip(msg.parsedData)}
                              className="flex items-center gap-2 px-3 py-1.5 bg-indigo-600 text-white rounded-lg text-xs font-medium hover:bg-indigo-700 transition-colors shadow-sm"
                          >
                              <Download className="w-3.5 h-3.5" />
                              Download ZIP
                          </motion.button>
                      </div>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div className="space-y-2">
                              <h4 className="text-xs font-bold uppercase text-gray-500 flex items-center gap-1">
                                  <FileText className="w-3 h-3" /> System Prompt
                              </h4>
                              <div className="bg-gray-50 p-3 rounded-lg text-xs font-mono h-32 overflow-y-auto border border-gray-200 scrollbar-thin scrollbar-thumb-gray-200">
                                  {msg.parsedData.systemPrompt}
                              </div>
                          </div>
                          <div className="space-y-2">
                              <h4 className="text-xs font-bold uppercase text-gray-500 flex items-center gap-1">
                                  <FileText className="w-3 h-3" /> User Prompt
                              </h4>
                              <div className="bg-gray-50 p-3 rounded-lg text-xs font-mono h-32 overflow-y-auto border border-gray-200 scrollbar-thin scrollbar-thumb-gray-200">
                                  {msg.parsedData.userPrompt}
                              </div>
                          </div>
                      </div>

                      <div className="space-y-2">
                          <h4 className="text-xs font-bold uppercase text-gray-500">Evaluation Criteria</h4>
                          <div className="bg-gray-50 p-3 rounded-lg text-xs border border-gray-200">
                              <Markdown>{msg.parsedData.evaluation}</Markdown>
                          </div>
                      </div>
                  </div>
                ) : (
                  <div className="markdown-body">
                    <Markdown>{msg.content}</Markdown>
                  </div>
                )}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>
        {isLoading && (
          <motion.div 
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex gap-3 max-w-[85%]"
          >
             <div className="w-8 h-8 rounded-full bg-white text-indigo-600 border border-gray-200 flex items-center justify-center flex-shrink-0 shadow-sm">
              <Bot className="w-4 h-4" />
            </div>
            <div className="bg-white border border-gray-100 p-4 rounded-2xl rounded-tl-none shadow-sm flex items-center">
              <div className="flex space-x-1">
                <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
                <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
                <div className="w-2 h-2 bg-indigo-400 rounded-full animate-bounce"></div>
              </div>
            </div>
          </motion.div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input Area */}
      <div className="p-4 bg-white border-t border-gray-100">
        <div className="relative flex items-end gap-2 max-w-4xl mx-auto">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Describe the role you need engineered..."
            className="w-full max-h-32 p-3 pr-12 bg-gray-50 border border-gray-200 rounded-xl focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 outline-none resize-none transition-all scrollbar-hide font-sans"
            rows={1}
            style={{ minHeight: '44px' }}
          />
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleSend}
            disabled={!input.trim() || isLoading}
            className={cn(
              "absolute right-2 bottom-2 p-2 rounded-lg transition-all",
              !input.trim() || isLoading
                ? "text-gray-400 bg-transparent"
                : "text-white bg-indigo-600 hover:bg-indigo-700 shadow-sm"
            )}
          >
            {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
          </motion.button>
        </div>
        <p className="text-center text-xs text-gray-400 mt-2">
          AI can make mistakes. Review generated responses.
        </p>
      </div>
    </div>
  );
}
